DROP TABLE IF EXISTS source_item;
DROP TABLE IF EXISTS target_item;
DROP TABLE IF EXISTS employee_source;
DROP TABLE IF EXISTS employee_target;

CREATE TABLE source_item (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL
);

CREATE TABLE target_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL,
    processed_name VARCHAR(150) NOT NULL,
    processed_at TIMESTAMP NOT NULL
);

CREATE TABLE employee_source (
    id BIGINT PRIMARY KEY,
    employee_no VARCHAR(30) NOT NULL,
    employee_name VARCHAR(100) NOT NULL,
    department VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL
);

CREATE TABLE employee_target (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_employee_id BIGINT NOT NULL,
    employee_no VARCHAR(30) NOT NULL,
    employee_name VARCHAR(100) NOT NULL,
    normalized_department VARCHAR(50) NOT NULL,
    processed_at TIMESTAMP NOT NULL
);
